[env]
ORT_STRATEGY = "compile"
ORT_COMPILE_VERSION = "1.17.1"
ORT_COMPILE_MINIMAL_BUILD = "ON"
ORT_COMPILE_EXTENDED_MINIMAL_BUILD = "OFF"
ORT_COMPILE_DISABLE_NNAPI = "ON"
ORT_COMPILE_DISABLE_RKNPU = "ON"
ORT_COMPILE_DISABLE_XNNPACK = "ON"
ORT_COMPILE_CMAKE_GENERATOR = "Unix Makefiles"

[target.x86_64-apple-darwin.env]
ORT_COMPILE_TARGET = "x86_64-apple-darwin"
ORT_COMPILE_CMAKE_EXTRA_DEFINES = "CMAKE_OSX_ARCHITECTURES=x86_64"

[target.aarch64-apple-darwin.env]
ORT_COMPILE_TARGET = "aarch64-apple-darwin"
ORT_COMPILE_CMAKE_EXTRA_DEFINES = "CMAKE_OSX_ARCHITECTURES=arm64"
