name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "src-tauri/**"
      - "package.json"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  build-ubuntu:
    uses: ./.github/workflows/ubuntu.yml
    with:
      release: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
